/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class DownloadTransformAlgorithmScheduleDto ( 
     val downloadTransformAlgorithmScheduleId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val downloadTransformGroupId : Long
     , val algorithmScheduleViewId : Long 
     ) extends BaseDto {  
   def tableName : String = {    "downloadTransformAlgorithmSchedule";    }  
   def fields : String = {    "downloadTransformAlgorithmScheduleId,guid,insertedRowDate,lastUpdatedDate,downloadTransformGroupId,algorithmScheduleViewId";    }  
   def pkFields : String = {    "downloadTransformAlgorithmScheduleId";    }  
   def fkFields : String = {    "algorithmScheduleViewId,downloadTransformGroupId";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    downloadTransformAlgorithmScheduleId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(downloadTransformAlgorithmScheduleId,guid,insertedRowDate,lastUpdatedDate,downloadTransformGroupId,algorithmScheduleViewId)  }  
 def toStringArray() : Array[String] = {    Array(""+downloadTransformAlgorithmScheduleId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+downloadTransformGroupId,""+algorithmScheduleViewId)   }  
 def toJson() : String = {   "{" + "\"downloadTransformAlgorithmScheduleId\":\""+downloadTransformAlgorithmScheduleId+"\""+","+"\"guid\":\""+guid+"\""+","+"\"insertedRowDate\":\""+insertedRowDate+"\""+","+"\"lastUpdatedDate\":\""+lastUpdatedDate+"\""+","+"\"downloadTransformGroupId\":\""+downloadTransformGroupId+"\""+","+"\"algorithmScheduleViewId\":\""+algorithmScheduleViewId+"\"" + "}"   }  
 def toFullString() : String = {    "downloadTransformAlgorithmScheduleId:'"+downloadTransformAlgorithmScheduleId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"downloadTransformGroupId:'"+downloadTransformGroupId+"'"+","+"algorithmScheduleViewId:'"+algorithmScheduleViewId+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "downloadTransformAlgorithmScheduleId" => downloadTransformAlgorithmScheduleId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "downloadTransformGroupId" => downloadTransformGroupId  
     case "algorithmScheduleViewId" => algorithmScheduleViewId   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "downloadTransformAlgorithmScheduleId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "downloadTransformGroupId" => "Long"  
     case "algorithmScheduleViewId" => "Long"   
    case _ => "Object" 
    } 
    ret 
  } 
   def prepareInsert(connection : java.sql.Connection) : java.sql.PreparedStatement = {
     val stat = connection.prepareStatement("insert into downloadTransformAlgorithmSchedule(guid,downloadTransformGroupId,algorithmScheduleViewId) values (?,?,?)", java.sql.Statement.RETURN_GENERATED_KEYS);
    stat.setObject(1, guid);
    stat.setObject(2, downloadTransformGroupId);
    stat.setObject(3, algorithmScheduleViewId);
    return stat; 
   } 
   def modify(downloadTransformGroupId : Long, algorithmScheduleViewId : Long) : DownloadTransformAlgorithmScheduleDto = {
    val dtoModified = new DownloadTransformAlgorithmScheduleDto(this.downloadTransformAlgorithmScheduleId,this.guid,this.insertedRowDate,new java.util.Date(),downloadTransformGroupId,algorithmScheduleViewId);
    dtoModified
  }
 } 
object DownloadTransformAlgorithmScheduleDto { 
  val TABLE_NAME = "downloadTransformAlgorithmSchedule"; 
   val FIELD_downloadTransformAlgorithmScheduleId = "downloadTransformAlgorithmScheduleId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_downloadTransformGroupId = "downloadTransformGroupId";
   val FIELD_algorithmScheduleViewId = "algorithmScheduleViewId";

  def createNewDownloadTransformAlgorithmScheduleDto(downloadTransformGroupId : Long, algorithmScheduleViewId : Long) : DownloadTransformAlgorithmScheduleDto = {  
     val dto = new DownloadTransformAlgorithmScheduleDto(0,0,new java.util.Date(),new java.util.Date(),downloadTransformGroupId,algorithmScheduleViewId)   
    dto 
  } 

}

 
