/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class DownloadTransformColumnDto ( 
     val downloadTransformColumnId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val downloadTransformTypeId : Long
     , val downloadTransformId : Long
     , val algorithmScheduleColumnId : Long
     , val sourceViewColumnId : Long
     , val downloadTransformDefinition : String 
     ) extends BaseDto {  
   def tableName : String = {    "downloadTransformColumn";    }  
   def fields : String = {    "downloadTransformColumnId,guid,insertedRowDate,lastUpdatedDate,downloadTransformTypeId,downloadTransformId,algorithmScheduleColumnId,sourceViewColumnId,downloadTransformDefinition";    }  
   def pkFields : String = {    "downloadTransformColumnId";    }  
   def fkFields : String = {    "algorithmScheduleColumnId,downloadTransformId,downloadTransformTypeId,sourceViewColumnId";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    downloadTransformColumnId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(downloadTransformColumnId,guid,insertedRowDate,lastUpdatedDate,downloadTransformTypeId,downloadTransformId,algorithmScheduleColumnId,sourceViewColumnId,downloadTransformDefinition)  }  
 def toStringArray() : Array[String] = {    Array(""+downloadTransformColumnId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+downloadTransformTypeId,""+downloadTransformId,""+algorithmScheduleColumnId,""+sourceViewColumnId,""+downloadTransformDefinition)   }  
 def toJson() : String = {   "{" + "\"downloadTransformColumnId\":\""+downloadTransformColumnId+"\""+","+"\"guid\":\""+guid+"\""+","+"\"insertedRowDate\":\""+insertedRowDate+"\""+","+"\"lastUpdatedDate\":\""+lastUpdatedDate+"\""+","+"\"downloadTransformTypeId\":\""+downloadTransformTypeId+"\""+","+"\"downloadTransformId\":\""+downloadTransformId+"\""+","+"\"algorithmScheduleColumnId\":\""+algorithmScheduleColumnId+"\""+","+"\"sourceViewColumnId\":\""+sourceViewColumnId+"\""+","+"\"downloadTransformDefinition\":\""+downloadTransformDefinition+"\"" + "}"   }  
 def toFullString() : String = {    "downloadTransformColumnId:'"+downloadTransformColumnId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"downloadTransformTypeId:'"+downloadTransformTypeId+"'"+","+"downloadTransformId:'"+downloadTransformId+"'"+","+"algorithmScheduleColumnId:'"+algorithmScheduleColumnId+"'"+","+"sourceViewColumnId:'"+sourceViewColumnId+"'"+","+"downloadTransformDefinition:'"+downloadTransformDefinition+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "downloadTransformColumnId" => downloadTransformColumnId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "downloadTransformTypeId" => downloadTransformTypeId  
     case "downloadTransformId" => downloadTransformId  
     case "algorithmScheduleColumnId" => algorithmScheduleColumnId  
     case "sourceViewColumnId" => sourceViewColumnId  
     case "downloadTransformDefinition" => downloadTransformDefinition   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "downloadTransformColumnId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "downloadTransformTypeId" => "Long"  
     case "downloadTransformId" => "Long"  
     case "algorithmScheduleColumnId" => "Long"  
     case "sourceViewColumnId" => "Long"  
     case "downloadTransformDefinition" => "String"   
    case _ => "Object" 
    } 
    ret 
  } 
   def prepareInsert(connection : java.sql.Connection) : java.sql.PreparedStatement = {
     val stat = connection.prepareStatement("insert into downloadTransformColumn(guid,downloadTransformTypeId,downloadTransformId,algorithmScheduleColumnId,sourceViewColumnId,downloadTransformDefinition) values (?,?,?,?,?,?)", java.sql.Statement.RETURN_GENERATED_KEYS);
    stat.setObject(1, guid);
    stat.setObject(2, downloadTransformTypeId);
    stat.setObject(3, downloadTransformId);
    stat.setObject(4, algorithmScheduleColumnId);
    stat.setObject(5, sourceViewColumnId);
    stat.setObject(6, downloadTransformDefinition);
    return stat; 
   } 
   def modify(downloadTransformTypeId : Long, downloadTransformId : Long, algorithmScheduleColumnId : Long, sourceViewColumnId : Long, downloadTransformDefinition : String) : DownloadTransformColumnDto = {
    val dtoModified = new DownloadTransformColumnDto(this.downloadTransformColumnId,this.guid,this.insertedRowDate,new java.util.Date(),downloadTransformTypeId,downloadTransformId,algorithmScheduleColumnId,sourceViewColumnId,downloadTransformDefinition);
    dtoModified
  }
 } 
object DownloadTransformColumnDto { 
  val TABLE_NAME = "downloadTransformColumn"; 
   val FIELD_downloadTransformColumnId = "downloadTransformColumnId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_downloadTransformTypeId = "downloadTransformTypeId";
   val FIELD_downloadTransformId = "downloadTransformId";
   val FIELD_algorithmScheduleColumnId = "algorithmScheduleColumnId";
   val FIELD_sourceViewColumnId = "sourceViewColumnId";
   val FIELD_downloadTransformDefinition = "downloadTransformDefinition";

  def createNewDownloadTransformColumnDto(downloadTransformTypeId : Long, downloadTransformId : Long, algorithmScheduleColumnId : Long, sourceViewColumnId : Long, downloadTransformDefinition : String) : DownloadTransformColumnDto = {  
     val dto = new DownloadTransformColumnDto(0,0,new java.util.Date(),new java.util.Date(),downloadTransformTypeId,downloadTransformId,algorithmScheduleColumnId,sourceViewColumnId,downloadTransformDefinition)   
    dto 
  } 

}

 
