/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class ExecutorCommandDto ( 
     val executorCommandId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val executorCommandName : String
     , val executorCommandClass : String 
     ) extends BaseDto {  
   def tableName : String = {    "executorCommand";    }  
   def fields : String = {    "executorCommandId,guid,insertedRowDate,lastUpdatedDate,executorCommandName,executorCommandClass";    }  
   def pkFields : String = {    "executorCommandId";    }  
   def fkFields : String = {    "";    }  
   def nameField : String = {    "executorCommandName";    }  
 def getPk() : Long = {    executorCommandId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(executorCommandId,guid,insertedRowDate,lastUpdatedDate,executorCommandName,executorCommandClass)  }  
 def toStringArray() : Array[String] = {    Array(""+executorCommandId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+executorCommandName,""+executorCommandClass)   }  
 def toJson() : String = {   "{" + "\"executorCommandId\":\""+executorCommandId+"\""+","+"\"guid\":\""+guid+"\""+","+"\"insertedRowDate\":\""+insertedRowDate+"\""+","+"\"lastUpdatedDate\":\""+lastUpdatedDate+"\""+","+"\"executorCommandName\":\""+executorCommandName+"\""+","+"\"executorCommandClass\":\""+executorCommandClass+"\"" + "}"   }  
 def toFullString() : String = {    "executorCommandId:'"+executorCommandId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"executorCommandName:'"+executorCommandName+"'"+","+"executorCommandClass:'"+executorCommandClass+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "executorCommandId" => executorCommandId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "executorCommandName" => executorCommandName  
     case "executorCommandClass" => executorCommandClass   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "executorCommandId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "executorCommandName" => "String"  
     case "executorCommandClass" => "String"   
    case _ => "Object" 
    } 
    ret 
  } 
   def prepareInsert(connection : java.sql.Connection) : java.sql.PreparedStatement = {
     val stat = connection.prepareStatement("insert into executorCommand(guid,executorCommandName,executorCommandClass) values (?,?,?)", java.sql.Statement.RETURN_GENERATED_KEYS);
    stat.setObject(1, guid);
    stat.setObject(2, executorCommandName);
    stat.setObject(3, executorCommandClass);
    return stat; 
   } 
   def modify(executorCommandName : String, executorCommandClass : String) : ExecutorCommandDto = {
    val dtoModified = new ExecutorCommandDto(this.executorCommandId,this.guid,this.insertedRowDate,new java.util.Date(),executorCommandName,executorCommandClass);
    dtoModified
  }
 } 
object ExecutorCommandDto { 
  val TABLE_NAME = "executorCommand"; 
   val FIELD_executorCommandId = "executorCommandId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_executorCommandName = "executorCommandName";
   val FIELD_executorCommandClass = "executorCommandClass";

  def createNewExecutorCommandDto(executorCommandName : String, executorCommandClass : String) : ExecutorCommandDto = {  
     val dto = new ExecutorCommandDto(0,0,new java.util.Date(),new java.util.Date(),executorCommandName,executorCommandClass)   
    dto 
  } 

}

 
