/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class SourceScheduleDto ( 
     val sourceScheduleId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val sourceViewId : Long
     , val executorStorageId : Long
     , val downloadTransformGroupId : Long
     , val onDemand : Int
     , val startTime : java.util.Date
     , val intervalValue : Long
     , val isScheduled : Int
     , val deleteOldCopies : Int 
     ) extends BaseDto {  
   def tableName : String = {    "sourceSchedule";    }  
   def fields : String = {    "sourceScheduleId,guid,insertedRowDate,lastUpdatedDate,sourceViewId,executorStorageId,downloadTransformGroupId,onDemand,startTime,intervalValue,isScheduled,deleteOldCopies";    }  
   def pkFields : String = {    "sourceScheduleId";    }  
   def fkFields : String = {    "downloadTransformGroupId,executorStorageId,sourceViewId";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    sourceScheduleId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(sourceScheduleId,guid,insertedRowDate,lastUpdatedDate,sourceViewId,executorStorageId,downloadTransformGroupId,onDemand,startTime,intervalValue,isScheduled,deleteOldCopies)  }  
 def toStringArray() : Array[String] = {    Array(""+sourceScheduleId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+sourceViewId,""+executorStorageId,""+downloadTransformGroupId,""+onDemand,""+startTime,""+intervalValue,""+isScheduled,""+deleteOldCopies)   }  
 def toJson() : String = {   "{" + "\"sourceScheduleId\":\""+sourceScheduleId+"\""+","+"\"guid\":\""+guid+"\""+","+"\"insertedRowDate\":\""+insertedRowDate+"\""+","+"\"lastUpdatedDate\":\""+lastUpdatedDate+"\""+","+"\"sourceViewId\":\""+sourceViewId+"\""+","+"\"executorStorageId\":\""+executorStorageId+"\""+","+"\"downloadTransformGroupId\":\""+downloadTransformGroupId+"\""+","+"\"onDemand\":\""+onDemand+"\""+","+"\"startTime\":\""+startTime+"\""+","+"\"intervalValue\":\""+intervalValue+"\""+","+"\"isScheduled\":\""+isScheduled+"\""+","+"\"deleteOldCopies\":\""+deleteOldCopies+"\"" + "}"   }  
 def toFullString() : String = {    "sourceScheduleId:'"+sourceScheduleId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"sourceViewId:'"+sourceViewId+"'"+","+"executorStorageId:'"+executorStorageId+"'"+","+"downloadTransformGroupId:'"+downloadTransformGroupId+"'"+","+"onDemand:'"+onDemand+"'"+","+"startTime:'"+startTime+"'"+","+"intervalValue:'"+intervalValue+"'"+","+"isScheduled:'"+isScheduled+"'"+","+"deleteOldCopies:'"+deleteOldCopies+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "sourceScheduleId" => sourceScheduleId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "sourceViewId" => sourceViewId  
     case "executorStorageId" => executorStorageId  
     case "downloadTransformGroupId" => downloadTransformGroupId  
     case "onDemand" => onDemand  
     case "startTime" => startTime  
     case "intervalValue" => intervalValue  
     case "isScheduled" => isScheduled  
     case "deleteOldCopies" => deleteOldCopies   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "sourceScheduleId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "sourceViewId" => "Long"  
     case "executorStorageId" => "Long"  
     case "downloadTransformGroupId" => "Long"  
     case "onDemand" => "Int"  
     case "startTime" => "java.util.Date"  
     case "intervalValue" => "Long"  
     case "isScheduled" => "Int"  
     case "deleteOldCopies" => "Int"   
    case _ => "Object" 
    } 
    ret 
  } 
   def prepareInsert(connection : java.sql.Connection) : java.sql.PreparedStatement = {
     val stat = connection.prepareStatement("insert into sourceSchedule(guid,sourceViewId,executorStorageId,downloadTransformGroupId,onDemand,startTime,intervalValue,isScheduled,deleteOldCopies) values (?,?,?,?,?,?,?,?,?)", java.sql.Statement.RETURN_GENERATED_KEYS);
    stat.setObject(1, guid);
    stat.setObject(2, sourceViewId);
    stat.setObject(3, executorStorageId);
    stat.setObject(4, downloadTransformGroupId);
    stat.setObject(5, onDemand);
    stat.setObject(6, startTime);
    stat.setObject(7, intervalValue);
    stat.setObject(8, isScheduled);
    stat.setObject(9, deleteOldCopies);
    return stat; 
   } 
   def modify(sourceViewId : Long, executorStorageId : Long, downloadTransformGroupId : Long, onDemand : Int, startTime : java.util.Date, intervalValue : Long, isScheduled : Int, deleteOldCopies : Int) : SourceScheduleDto = {
    val dtoModified = new SourceScheduleDto(this.sourceScheduleId,this.guid,this.insertedRowDate,new java.util.Date(),sourceViewId,executorStorageId,downloadTransformGroupId,onDemand,startTime,intervalValue,isScheduled,deleteOldCopies);
    dtoModified
  }
 } 
object SourceScheduleDto { 
  val TABLE_NAME = "sourceSchedule"; 
   val FIELD_sourceScheduleId = "sourceScheduleId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_sourceViewId = "sourceViewId";
   val FIELD_executorStorageId = "executorStorageId";
   val FIELD_downloadTransformGroupId = "downloadTransformGroupId";
   val FIELD_onDemand = "onDemand";
   val FIELD_startTime = "startTime";
   val FIELD_intervalValue = "intervalValue";
   val FIELD_isScheduled = "isScheduled";
   val FIELD_deleteOldCopies = "deleteOldCopies";

  def createNewSourceScheduleDto(sourceViewId : Long, executorStorageId : Long, downloadTransformGroupId : Long, onDemand : Int, startTime : java.util.Date, intervalValue : Long, isScheduled : Int, deleteOldCopies : Int) : SourceScheduleDto = {  
     val dto = new SourceScheduleDto(0,0,new java.util.Date(),new java.util.Date(),sourceViewId,executorStorageId,downloadTransformGroupId,onDemand,startTime,intervalValue,isScheduled,deleteOldCopies)   
    dto 
  } 

}

 
