/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class VDownloadTransformGroupSummaryDto ( 
     val downloadTransformGroupId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val downloadTransformGroupName : String
     , val downloadTransformGroupDescription : String
     , val sourceDownload_count : Int
     , val executorStorageView_count : Int
     , val downloadTransformAlgorithmSchedule_count : Int
     , val downloadTransformExecutorStorage_count : Int
     , val downloadTransform_count : Int
     , val sourceSchedule_count : Int 
     ) extends BaseReadOnlyDto {  
   def tableName : String = {    "vDownloadTransformGroupSummary";    }  
   def fields : String = {    "downloadTransformGroupId,guid,insertedRowDate,lastUpdatedDate,downloadTransformGroupName,downloadTransformGroupDescription,sourceDownload_count,executorStorageView_count,downloadTransformAlgorithmSchedule_count,downloadTransformExecutorStorage_count,downloadTransform_count,sourceSchedule_count";    }  
   def pkFields : String = {    "";    }  
   def fkFields : String = {    "";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    downloadTransformGroupId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(downloadTransformGroupId,guid,insertedRowDate,lastUpdatedDate,downloadTransformGroupName,downloadTransformGroupDescription,sourceDownload_count,executorStorageView_count,downloadTransformAlgorithmSchedule_count,downloadTransformExecutorStorage_count,downloadTransform_count,sourceSchedule_count)  }  
 def toStringArray() : Array[String] = {    Array(""+downloadTransformGroupId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+downloadTransformGroupName,""+downloadTransformGroupDescription,""+sourceDownload_count,""+executorStorageView_count,""+downloadTransformAlgorithmSchedule_count,""+downloadTransformExecutorStorage_count,""+downloadTransform_count,""+sourceSchedule_count)   }  
 def toJson() : String = {   "{" + "\"downloadTransformGroupId\":\""+downloadTransformGroupId+"\""+","+"\"guid\":\""+guid+"\""+","+"\"insertedRowDate\":\""+insertedRowDate+"\""+","+"\"lastUpdatedDate\":\""+lastUpdatedDate+"\""+","+"\"downloadTransformGroupName\":\""+downloadTransformGroupName+"\""+","+"\"downloadTransformGroupDescription\":\""+downloadTransformGroupDescription+"\""+","+"\"sourceDownload_count\":\""+sourceDownload_count+"\""+","+"\"executorStorageView_count\":\""+executorStorageView_count+"\""+","+"\"downloadTransformAlgorithmSchedule_count\":\""+downloadTransformAlgorithmSchedule_count+"\""+","+"\"downloadTransformExecutorStorage_count\":\""+downloadTransformExecutorStorage_count+"\""+","+"\"downloadTransform_count\":\""+downloadTransform_count+"\""+","+"\"sourceSchedule_count\":\""+sourceSchedule_count+"\"" + "}"   }  
 def toFullString() : String = {    "downloadTransformGroupId:'"+downloadTransformGroupId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"downloadTransformGroupName:'"+downloadTransformGroupName+"'"+","+"downloadTransformGroupDescription:'"+downloadTransformGroupDescription+"'"+","+"sourceDownload_count:'"+sourceDownload_count+"'"+","+"executorStorageView_count:'"+executorStorageView_count+"'"+","+"downloadTransformAlgorithmSchedule_count:'"+downloadTransformAlgorithmSchedule_count+"'"+","+"downloadTransformExecutorStorage_count:'"+downloadTransformExecutorStorage_count+"'"+","+"downloadTransform_count:'"+downloadTransform_count+"'"+","+"sourceSchedule_count:'"+sourceSchedule_count+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "downloadTransformGroupId" => downloadTransformGroupId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "downloadTransformGroupName" => downloadTransformGroupName  
     case "downloadTransformGroupDescription" => downloadTransformGroupDescription  
     case "sourceDownload_count" => sourceDownload_count  
     case "executorStorageView_count" => executorStorageView_count  
     case "downloadTransformAlgorithmSchedule_count" => downloadTransformAlgorithmSchedule_count  
     case "downloadTransformExecutorStorage_count" => downloadTransformExecutorStorage_count  
     case "downloadTransform_count" => downloadTransform_count  
     case "sourceSchedule_count" => sourceSchedule_count   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "downloadTransformGroupId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "downloadTransformGroupName" => "String"  
     case "downloadTransformGroupDescription" => "String"  
     case "sourceDownload_count" => "Int"  
     case "executorStorageView_count" => "Int"  
     case "downloadTransformAlgorithmSchedule_count" => "Int"  
     case "downloadTransformExecutorStorage_count" => "Int"  
     case "downloadTransform_count" => "Int"  
     case "sourceSchedule_count" => "Int"   
    case _ => "Object" 
    } 
    ret 
  } 
 } 
object VDownloadTransformGroupSummaryDto { 
  val TABLE_NAME = "vDownloadTransformGroupSummary"; 
   val FIELD_downloadTransformGroupId = "downloadTransformGroupId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_downloadTransformGroupName = "downloadTransformGroupName";
   val FIELD_downloadTransformGroupDescription = "downloadTransformGroupDescription";
   val FIELD_sourceDownload_count = "sourceDownload_count";
   val FIELD_executorStorageView_count = "executorStorageView_count";
   val FIELD_downloadTransformAlgorithmSchedule_count = "downloadTransformAlgorithmSchedule_count";
   val FIELD_downloadTransformExecutorStorage_count = "downloadTransformExecutorStorage_count";
   val FIELD_downloadTransform_count = "downloadTransform_count";
   val FIELD_sourceSchedule_count = "sourceSchedule_count";

}

 
