/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class VDownloadTransformDto ( 
     val downloadTransformId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val downloadTransformTypeId : Long
     , val downloadTransformGroupId : Long
     , val downloadTransformDefinition : String
     , val downloadTransformGroup_downloadTransformGroupId : Long
     , val downloadTransformGroup_guid : Long
     , val downloadTransformGroup_insertedRowDate : java.util.Date
     , val downloadTransformGroup_lastUpdatedDate : java.util.Date
     , val downloadTransformGroup_downloadTransformGroupName : String
     , val downloadTransformGroup_downloadTransformGroupDescription : String
     , val downloadTransformType_downloadTransformTypeId : Long
     , val downloadTransformType_guid : Long
     , val downloadTransformType_insertedRowDate : java.util.Date
     , val downloadTransformType_lastUpdatedDate : java.util.Date
     , val downloadTransformType_downloadTransformTypeName : String
     , val downloadTransformType_downloadTransformTypeClass : String 
     ) extends BaseReadOnlyDto {  
   def tableName : String = {    "vDownloadTransform";    }  
   def fields : String = {    "downloadTransformId,guid,insertedRowDate,lastUpdatedDate,downloadTransformTypeId,downloadTransformGroupId,downloadTransformDefinition,downloadTransformGroup_downloadTransformGroupId,downloadTransformGroup_guid,downloadTransformGroup_insertedRowDate,downloadTransformGroup_lastUpdatedDate,downloadTransformGroup_downloadTransformGroupName,downloadTransformGroup_downloadTransformGroupDescription,downloadTransformType_downloadTransformTypeId,downloadTransformType_guid,downloadTransformType_insertedRowDate,downloadTransformType_lastUpdatedDate,downloadTransformType_downloadTransformTypeName,downloadTransformType_downloadTransformTypeClass";    }  
   def pkFields : String = {    "";    }  
   def fkFields : String = {    "";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    downloadTransformId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(downloadTransformId,guid,insertedRowDate,lastUpdatedDate,downloadTransformTypeId,downloadTransformGroupId,downloadTransformDefinition,downloadTransformGroup_downloadTransformGroupId,downloadTransformGroup_guid,downloadTransformGroup_insertedRowDate,downloadTransformGroup_lastUpdatedDate,downloadTransformGroup_downloadTransformGroupName,downloadTransformGroup_downloadTransformGroupDescription,downloadTransformType_downloadTransformTypeId,downloadTransformType_guid,downloadTransformType_insertedRowDate,downloadTransformType_lastUpdatedDate,downloadTransformType_downloadTransformTypeName,downloadTransformType_downloadTransformTypeClass)  }  
 def toStringArray() : Array[String] = {    Array(""+downloadTransformId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+downloadTransformTypeId,""+downloadTransformGroupId,""+downloadTransformDefinition,""+downloadTransformGroup_downloadTransformGroupId,""+downloadTransformGroup_guid,""+downloadTransformGroup_insertedRowDate,""+downloadTransformGroup_lastUpdatedDate,""+downloadTransformGroup_downloadTransformGroupName,""+downloadTransformGroup_downloadTransformGroupDescription,""+downloadTransformType_downloadTransformTypeId,""+downloadTransformType_guid,""+downloadTransformType_insertedRowDate,""+downloadTransformType_lastUpdatedDate,""+downloadTransformType_downloadTransformTypeName,""+downloadTransformType_downloadTransformTypeClass)   }  
 def toJson() : String = {   "{" + "\"downloadTransformId\":\""+downloadTransformId+"\""+","+"\"guid\":\""+guid+"\""+","+"\"insertedRowDate\":\""+insertedRowDate+"\""+","+"\"lastUpdatedDate\":\""+lastUpdatedDate+"\""+","+"\"downloadTransformTypeId\":\""+downloadTransformTypeId+"\""+","+"\"downloadTransformGroupId\":\""+downloadTransformGroupId+"\""+","+"\"downloadTransformDefinition\":\""+downloadTransformDefinition+"\""+","+"\"downloadTransformGroup_downloadTransformGroupId\":\""+downloadTransformGroup_downloadTransformGroupId+"\""+","+"\"downloadTransformGroup_guid\":\""+downloadTransformGroup_guid+"\""+","+"\"downloadTransformGroup_insertedRowDate\":\""+downloadTransformGroup_insertedRowDate+"\""+","+"\"downloadTransformGroup_lastUpdatedDate\":\""+downloadTransformGroup_lastUpdatedDate+"\""+","+"\"downloadTransformGroup_downloadTransformGroupName\":\""+downloadTransformGroup_downloadTransformGroupName+"\""+","+"\"downloadTransformGroup_downloadTransformGroupDescription\":\""+downloadTransformGroup_downloadTransformGroupDescription+"\""+","+"\"downloadTransformType_downloadTransformTypeId\":\""+downloadTransformType_downloadTransformTypeId+"\""+","+"\"downloadTransformType_guid\":\""+downloadTransformType_guid+"\""+","+"\"downloadTransformType_insertedRowDate\":\""+downloadTransformType_insertedRowDate+"\""+","+"\"downloadTransformType_lastUpdatedDate\":\""+downloadTransformType_lastUpdatedDate+"\""+","+"\"downloadTransformType_downloadTransformTypeName\":\""+downloadTransformType_downloadTransformTypeName+"\""+","+"\"downloadTransformType_downloadTransformTypeClass\":\""+downloadTransformType_downloadTransformTypeClass+"\"" + "}"   }  
 def toFullString() : String = {    "downloadTransformId:'"+downloadTransformId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"downloadTransformTypeId:'"+downloadTransformTypeId+"'"+","+"downloadTransformGroupId:'"+downloadTransformGroupId+"'"+","+"downloadTransformDefinition:'"+downloadTransformDefinition+"'"+","+"downloadTransformGroup_downloadTransformGroupId:'"+downloadTransformGroup_downloadTransformGroupId+"'"+","+"downloadTransformGroup_guid:'"+downloadTransformGroup_guid+"'"+","+"downloadTransformGroup_insertedRowDate:'"+downloadTransformGroup_insertedRowDate+"'"+","+"downloadTransformGroup_lastUpdatedDate:'"+downloadTransformGroup_lastUpdatedDate+"'"+","+"downloadTransformGroup_downloadTransformGroupName:'"+downloadTransformGroup_downloadTransformGroupName+"'"+","+"downloadTransformGroup_downloadTransformGroupDescription:'"+downloadTransformGroup_downloadTransformGroupDescription+"'"+","+"downloadTransformType_downloadTransformTypeId:'"+downloadTransformType_downloadTransformTypeId+"'"+","+"downloadTransformType_guid:'"+downloadTransformType_guid+"'"+","+"downloadTransformType_insertedRowDate:'"+downloadTransformType_insertedRowDate+"'"+","+"downloadTransformType_lastUpdatedDate:'"+downloadTransformType_lastUpdatedDate+"'"+","+"downloadTransformType_downloadTransformTypeName:'"+downloadTransformType_downloadTransformTypeName+"'"+","+"downloadTransformType_downloadTransformTypeClass:'"+downloadTransformType_downloadTransformTypeClass+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "downloadTransformId" => downloadTransformId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "downloadTransformTypeId" => downloadTransformTypeId  
     case "downloadTransformGroupId" => downloadTransformGroupId  
     case "downloadTransformDefinition" => downloadTransformDefinition  
     case "downloadTransformGroup_downloadTransformGroupId" => downloadTransformGroup_downloadTransformGroupId  
     case "downloadTransformGroup_guid" => downloadTransformGroup_guid  
     case "downloadTransformGroup_insertedRowDate" => downloadTransformGroup_insertedRowDate  
     case "downloadTransformGroup_lastUpdatedDate" => downloadTransformGroup_lastUpdatedDate  
     case "downloadTransformGroup_downloadTransformGroupName" => downloadTransformGroup_downloadTransformGroupName  
     case "downloadTransformGroup_downloadTransformGroupDescription" => downloadTransformGroup_downloadTransformGroupDescription  
     case "downloadTransformType_downloadTransformTypeId" => downloadTransformType_downloadTransformTypeId  
     case "downloadTransformType_guid" => downloadTransformType_guid  
     case "downloadTransformType_insertedRowDate" => downloadTransformType_insertedRowDate  
     case "downloadTransformType_lastUpdatedDate" => downloadTransformType_lastUpdatedDate  
     case "downloadTransformType_downloadTransformTypeName" => downloadTransformType_downloadTransformTypeName  
     case "downloadTransformType_downloadTransformTypeClass" => downloadTransformType_downloadTransformTypeClass   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "downloadTransformId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "downloadTransformTypeId" => "Long"  
     case "downloadTransformGroupId" => "Long"  
     case "downloadTransformDefinition" => "String"  
     case "downloadTransformGroup_downloadTransformGroupId" => "Long"  
     case "downloadTransformGroup_guid" => "Long"  
     case "downloadTransformGroup_insertedRowDate" => "java.util.Date"  
     case "downloadTransformGroup_lastUpdatedDate" => "java.util.Date"  
     case "downloadTransformGroup_downloadTransformGroupName" => "String"  
     case "downloadTransformGroup_downloadTransformGroupDescription" => "String"  
     case "downloadTransformType_downloadTransformTypeId" => "Long"  
     case "downloadTransformType_guid" => "Long"  
     case "downloadTransformType_insertedRowDate" => "java.util.Date"  
     case "downloadTransformType_lastUpdatedDate" => "java.util.Date"  
     case "downloadTransformType_downloadTransformTypeName" => "String"  
     case "downloadTransformType_downloadTransformTypeClass" => "String"   
    case _ => "Object" 
    } 
    ret 
  } 
 } 
object VDownloadTransformDto { 
  val TABLE_NAME = "vDownloadTransform"; 
   val FIELD_downloadTransformId = "downloadTransformId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_downloadTransformTypeId = "downloadTransformTypeId";
   val FIELD_downloadTransformGroupId = "downloadTransformGroupId";
   val FIELD_downloadTransformDefinition = "downloadTransformDefinition";
   val FIELD_downloadTransformGroup_downloadTransformGroupId = "downloadTransformGroup_downloadTransformGroupId";
   val FIELD_downloadTransformGroup_guid = "downloadTransformGroup_guid";
   val FIELD_downloadTransformGroup_insertedRowDate = "downloadTransformGroup_insertedRowDate";
   val FIELD_downloadTransformGroup_lastUpdatedDate = "downloadTransformGroup_lastUpdatedDate";
   val FIELD_downloadTransformGroup_downloadTransformGroupName = "downloadTransformGroup_downloadTransformGroupName";
   val FIELD_downloadTransformGroup_downloadTransformGroupDescription = "downloadTransformGroup_downloadTransformGroupDescription";
   val FIELD_downloadTransformType_downloadTransformTypeId = "downloadTransformType_downloadTransformTypeId";
   val FIELD_downloadTransformType_guid = "downloadTransformType_guid";
   val FIELD_downloadTransformType_insertedRowDate = "downloadTransformType_insertedRowDate";
   val FIELD_downloadTransformType_lastUpdatedDate = "downloadTransformType_lastUpdatedDate";
   val FIELD_downloadTransformType_downloadTransformTypeName = "downloadTransformType_downloadTransformTypeName";
   val FIELD_downloadTransformType_downloadTransformTypeClass = "downloadTransformType_downloadTransformTypeClass";

}

 
