/*
  Author(s): Slawomir Bankowski
  Project: mlasaf
  AUTOGENERATED CODE
*/
package com.mlasaf.dto 
 
 
case class VExecutorStorageSnapshotSummaryDto ( 
     val executorStorageSnapshotId : Long
     , val guid : Long
     , val insertedRowDate : java.util.Date
     , val lastUpdatedDate : java.util.Date
     , val executorInstanceId : Long
     , val executorStorageView_count : Int 
     ) extends BaseReadOnlyDto {  
   def tableName : String = {    "vExecutorStorageSnapshotSummary";    }  
   def fields : String = {    "executorStorageSnapshotId,guid,insertedRowDate,lastUpdatedDate,executorInstanceId,executorStorageView_count";    }  
   def pkFields : String = {    "";    }  
   def fkFields : String = {    "";    }  
   def nameField : String = {    "";    }  
 def getPk() : Long = {    executorStorageSnapshotId  }  
 def getInsertedRowDate() : java.util.Date = {    insertedRowDate  }  
 def getLastUpdatedDate() : java.util.Date = {    lastUpdatedDate  }  
 def getGuid() : Long = {    guid  }  
 def toAnyArray() : Array[Any] = {    Array(executorStorageSnapshotId,guid,insertedRowDate,lastUpdatedDate,executorInstanceId,executorStorageView_count)  }  
 def toStringArray() : Array[String] = {    Array(""+executorStorageSnapshotId,""+guid,""+insertedRowDate,""+lastUpdatedDate,""+executorInstanceId,""+executorStorageView_count)   }  
 def toJson() : String = {   "{" + "\"executorStorageSnapshotId\":\""+executorStorageSnapshotId+"\""+","+"\"guid\":\""+guid+"\""+","+"\"insertedRowDate\":\""+insertedRowDate+"\""+","+"\"lastUpdatedDate\":\""+lastUpdatedDate+"\""+","+"\"executorInstanceId\":\""+executorInstanceId+"\""+","+"\"executorStorageView_count\":\""+executorStorageView_count+"\"" + "}"   }  
 def toFullString() : String = {    "executorStorageSnapshotId:'"+executorStorageSnapshotId+"'"+","+"guid:'"+guid+"'"+","+"insertedRowDate:'"+insertedRowDate+"'"+","+"lastUpdatedDate:'"+lastUpdatedDate+"'"+","+"executorInstanceId:'"+executorInstanceId+"'"+","+"executorStorageView_count:'"+executorStorageView_count+"'"   } 
   def getFieldValue(name : String) : Any = { 
    val ret = name match { 
    case "executorStorageSnapshotId" => executorStorageSnapshotId  
     case "guid" => guid  
     case "insertedRowDate" => insertedRowDate  
     case "lastUpdatedDate" => lastUpdatedDate  
     case "executorInstanceId" => executorInstanceId  
     case "executorStorageView_count" => executorStorageView_count   
    case _ => null 
    } 
    ret 
  } 
   def getFieldTypeName(name : String) : String = { 
    val ret = name match { 
    case "executorStorageSnapshotId" => "Long"  
     case "guid" => "Long"  
     case "insertedRowDate" => "java.util.Date"  
     case "lastUpdatedDate" => "java.util.Date"  
     case "executorInstanceId" => "Long"  
     case "executorStorageView_count" => "Int"   
    case _ => "Object" 
    } 
    ret 
  } 
 } 
object VExecutorStorageSnapshotSummaryDto { 
  val TABLE_NAME = "vExecutorStorageSnapshotSummary"; 
   val FIELD_executorStorageSnapshotId = "executorStorageSnapshotId";
   val FIELD_guid = "guid";
   val FIELD_insertedRowDate = "insertedRowDate";
   val FIELD_lastUpdatedDate = "lastUpdatedDate";
   val FIELD_executorInstanceId = "executorInstanceId";
   val FIELD_executorStorageView_count = "executorStorageView_count";

}

 
